kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: nifi
  name: nifi-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: nifi
  name: nifi-pv
  labels:
    type: local
spec:
  storageClassName: nifi-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nifi"